assert check

diff --git a/.github/workflows/build-push.yml b/.github/workflows/build-push.yml
--- a/.github/workflows/build-push.yml
+++ b/.github/workflows/build-push.yml
@@ -133,6 +133,20 @@ jobs:
       - name: check if file_error detected
         run: |
           find ./test/ocr/corruptmovie -name 'file_error' | grep -c 'file_error'
+      - name: kill leader detect check (failure)
+        run: |
+          cnt=$(grep -c ',8,' ./test/ocr/2023-08-15_23-10-50/cut_time_battle.csv || true)
+          if [ $cnt -ne 0 ]; then
+            echo "[ERROR] 2023-08-15_23-10-50/cut_time_battle.csv have kill(8) record."
+            exit 1
+          fi
+      - name: kill leader detect check
+        run: |
+          cnt=$(grep -c ',8,' ./test/ocr/2023-08-15_23-10-49/cut_time_battle.csv || true)
+          if [ $cnt -eq 0 ]; then
+            echo "[ERROR] 2023-08-15_23-10-49/cut_time_battle.csv doesn't have kill record."
+            exit 1
+          fi
       - name: save ocr artifact
         uses: actions/upload-artifact@v3
         with:
