file_error時にエラー出力するStepを追加

diff --git a/.github/workflows/build-push.yml b/.github/workflows/build-push.yml
--- a/.github/workflows/build-push.yml
+++ b/.github/workflows/build-push.yml
@@ -147,6 +147,14 @@ jobs:
             echo "[ERROR] 2023-08-15_23-10-49/cut_time_battle.csv doesn't have kill record."
             exit 1
           fi
+      - name: check file_error
+        run: |
+          cnt=$(find ./test/ocr -name "file_error" | grep -c file_error || true)
+          if [ $cnt -eq 0 ]; then
+            echo "[ERROR] file_error detected"
+            find ./test/ocr -name "file_error"
+            exit 1
+          fi
       - name: save ocr artifact
         uses: actions/upload-artifact@v3
         with:
